### ISSUE TITLE
Wirecloud 1.3 simple returns 403 on all WireCloud's proxy requests

### ISSUE THREAD

**Issue by jenisov** [Wirecloud/wirecloud#472] opened 2020-02-19 21:14 UTC
After logging in with superuser and adding NGSI browser widget it shows message:

> ConnectionError: You aren't allowed to use the WireCloud's proxy. Have you signed off from WireCloud?

Chrome debug console says:

> GET http://iotcloud:1080/cdp/http/iotcloud/orion/v2/entities?limit=20&offset=0&options=count%2CkeyValues&idPattern=.* 403 (Forbidden)

The only change in setup is listen nginx on port 1080 and settings.py was mounted with FORCE_DOMAIN and FORCE_PORT set to proper values.

**Comment by jenisov** [comment] 2020-02-20 11:17
Sorry if wrong place for the issue, duplicated to https://github.com/Wirecloud/docker-wirecloud/issues/53.

**Comment by aarranz** [comment] 2020-02-24 10:07
Let's close this ticket for now, because I guess the problem is on the docker integration. We can reopen it if the problem is not related with docker integration.

**Closed as completed by aarranz** 2020-02-24 10:07 UTC
